### PR TITLE
fix: MemoryHealthChecker do query will panic

### LINKED ISSUE #142: MemoryHealthChecker do query will panic
**Describe the bug**

https://github.com/polarismesh/polaris/blob/b126c26ab77c0920e04fba32e337357ae643b3d1/plugin/healthchecker/heartbeatmemory/checker_memory.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L74

```golang
func (r *MemoryHealthChecker) Query(request *plugin.QueryRequest) (*plugin.QueryResponse, error) {
	recordValue, ok := r.hbRecords.Load(request.InstanceId)
	if !ok {
		return &plugin.QueryResponse{
			LastHeartbeatSec: 0,
		}, nil
	}
	record := recordValue.(*HeartbeatRecord)
	return &plugin.QueryResponse{
		Server:           record.Server,
		LastHeartbeatSec: record.CurTimeSec,
	}, nil
}
```

this code will let polaris-server occur panic: `record := recordValue.(*HeartbeatRecord)`

Correct code is `record := recordValue.(HeartbeatRecord)`

**To Reproduce**

1. set healthchecktype is memory
```yaml
healthcheck:
  open: true
  service: polaris.checker
  slotNum: 30
  checkers:
    - name: heartbeatMemory
```
2. run polaris-server
3. register instance and send heartbeat to polaris-server

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

### PR DESCRIPTION
**Pull request by DHBin**
**Please provide issue(s) of this PR:
Fixes #142 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [x] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by chuntaojun — APPROVED** [review]

**Comment by chuntaojun** [comment]
LGTM

File: plugin/healthchecker/heartbeatmemory/checker_memory_test.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
+package heartbeatmemory
```
Comment (andrewshan) [inline plugin/healthchecker/heartbeatmemory/checker_memory_test.go:1]: hello, pls add the copyright headers to this source code to make workflow passed

Comment (DHBin) [reply plugin/healthchecker/heartbeatmemory/checker_memory_test.go:18]: added
