### PR TITLE
fix: #751 timewheel用来做轮转任务会每轮增加timewheel.interval时间的问题

### LINKED ISSUE #751: timewheel用来做轮转任务会每轮增加timewheel.interval时间的问题
由于目前时间轮的设计是当前时间刻度走完才执行当前刻度的任务，会导致在callback方法中递归AddTask的时间延迟一个时间刻度那么长的时间。
例如，当前轮盘分为4个slots，在刻度0(slots[0])有task1等待执行，task1的轮转周期为一个轮盘时间(即刚好一圈)。
当时间来到刻度1的时候，会开始执行刻度0的task1，执行task1的时候currentPos会赋值为1(由于运行task是开新的协程执行，一般currentPos会先自增)，此时执行到callback方法的AddTask方法会将当前任务放到刻度为1的task链。
由于task1的周期是1圈，所以我们期望task1是应该放回原来刻度0的位置的，结果是放到了刻度1的位置，而刻度1在第二圈会有刻度2的时间去执行。

是否可以通过更改时间轮的设计来完善，当时间走到刻度0的时候执行刻度0的task，时间走到刻度1执行刻度1的task？

### PR DESCRIPTION
**Pull request by hoErYu**
**Please provide issue(s) of this PR:**
Fixes #751

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: common/timewheel/timewheel_test.go [hunk 1]
```diff
@@ -210,3 +212,33 @@ func TestSelect(t *testing.T) {
...
+
+func TestRotationTask(t *testing.T) {
+	tw := New(time.Second, 5, "")
+	tw.Start()
+	rotationCallback(t, tw, 1, 0, time.Now().UnixMilli())
+	rotationCallback(t, tw, 3, 0, time.Now().UnixMilli())
+	rotationCallback(t, tw, 5, 0, time.Now().UnixMilli())
+	rotationCallback(t, tw, 10, 0, time.Now().UnixMilli())
+	rotationCallback(t, tw, 12, 0, time.Now().UnixMilli())
+	time.Sleep(62 * time.Second)
```
Comment (chuntaojun) [inline common/timewheel/timewheel_test.go:224]: 建议使用 sync.WaitGroup 来做等待测试用例的结束，然后每一个 rotationCallback 建议单独的 t.Run("", func(t *testing.T){}) 来处理

File: common/timewheel/timewheel_test.go [hunk 2]
```diff
@@ -210,3 +212,33 @@ func TestSelect(t *testing.T) {
...
+func rotationCallback(t *testing.T, tw *TimeWheel, intervalSecond int64, runTimes int, lastTime int64) {
+	tw.AddTask(uint32(intervalSecond*time.Second.Milliseconds()), nil, func(i interface{}) {
+		//0.800-1.200
+		fmt.Println(time.Now())
+		interval := time.Now().UnixMilli() - lastTime
+		if runTimes == 0 {
+			//首次减去时间轮启动的刻度时间
+			interval = interval - tw.interval.Milliseconds()
+		}
+		assert.True(t, interval > intervalSecond*1000+-200 && interval < intervalSecond*1000+200)
```
Comment (chuntaojun) [inline common/timewheel/timewheel_test.go:237]: diff := math.Abs(float64(interval - intervalSecond*1000))
assert.True(t, diff < 200)

File: common/timewheel/timewheel.go [hunk 3]
```diff
@@ -72,6 +75,11 @@ func New(interval time.Duration, slotNum int, name string) *TimeWheel {
 	return timeWheel
 }
 
+func (tw *TimeWheel) ForceCloseMode() *TimeWheel {
```
Comment (chuntaojun) [inline common/timewheel/timewheel.go:78]: 建议调整 New 这个构造函数为 Options 模式

**Review by chuntaojun — APPROVED** [review]
