### PR TITLE
fix req.metadata map nil

### LINKED ISSUE #961: GetLastHeartbeat req metadata map没有初始化
**Describe the bug**
GetLastHeartbeat req metadata map没有初始化

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: 1.14
- OS: [e.g. CentOS8]

**Additional context**

### PR DESCRIPTION
**Pull request by movebean**
**Please provide issue(s) of this PR:**
Fixes #961

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] ApiServer
- [ ] Auth
- [ ] Configuration
- [ ] Naming
- [ ] HealthCheck
- [ ] Metrics
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

File: service/healthcheck/server.go [hunk 1]
```diff
@@ -262,6 +262,9 @@ func (s *Server) GetLastHeartbeat(req *apiservice.Instance) *apiservice.Response
 	req.Port = insCache.Proto.Port
 	req.VpcId = insCache.Proto.GetVpcId()
 	req.HealthCheck = insCache.Proto.GetHealthCheck()
+	if req.Metadata == nil {
```
Comment (andrewshan) [inline service/healthcheck/server.go:265]: 去掉判空

Comment (movebean) [reply service/healthcheck/server.go]: OK

**Review by andrewshan — APPROVED** [review]
LGTM
