### PR TITLE
fix: escaped sql scripts make database deadlock

### LINKED ISSUE #953: MySQL deadlock make cache update suspend for long time
**Describe the bug**
20:19:47到20:21：数据库同时出现了多个实例的写入，实例写入过程中，同时发生了cleanservice的操作。
20:20到20:21：出现了数据库deadlock
image

20:20到20:21：这段时间，缓存没有加载，实例一直从缓存中获取失败
image

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
缓存加载正常，数据库deadlock不会出现

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

### PR DESCRIPTION
**Pull request by andrewshan**
**Please provide issue(s) of this PR:**
Fixes #953 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] ApiServer
- [ ] Auth
- [ ] Configuration
- [x] Naming
- [ ] HealthCheck
- [ ] Metrics
- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

### CODE REVIEW

**Review by chuntaojun — APPROVED** [review]

File: store/mysql/group.go [hunk 1]
```diff
@@ -83,6 +78,11 @@ func (u *groupStore) addGroup(group *model.UserGroupDetail) error {
 
 	defer func() { _ = tx.Rollback() }()
 
+	// 先清理无效数据
+	if err := u.cleanInValidGroup(group.Name, group.Owner); err != nil {
```
Comment (chuntaojun) [inline store/mysql/group.go:82]: 这个还是不在一个 tx 里面，必须显示传入 tx

**Review by daheige — APPROVED** [review]

File: store/mysql/client.go [hunk 2]
```diff
@@ -305,6 +301,10 @@ func (cs *clientStore) createClient(client *model.Client) error {
 		return err
 	}
 	defer func() { _ = tx.Rollback() }()
+	// clean the old items before add
+	if err := cs.deleteClient(client.Proto().GetId().GetValue()); err != nil {
```
Comment (chuntaojun) [inline store/mysql/client.go:305]: 不在一个事务里面

**Review by chuntaojun — APPROVED** [review]
